# Generated by Django 5.2.7 on 2025-10-06 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('wood', 'Wood'), ('furniture', 'Furniture')], max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(blank=True, max_length=30, null=True)),
                ('measurements', models.CharField(blank=True, max_length=100, null=True)),
                ('quality', models.CharField(max_length=50)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_stock', models.PositiveIntegerField(default=0)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
